import "./index.css";
import axios from "axios";
import { useState, useEffect } from "react";

export function App() {
  return (
    <div className="app">
      {/*
      we should call the backend here to get the visitor count.
      Flow:
      - When an user accesses a page, call the post endpoint to bump the visit counter by 1.
      - Then, return the counter from the endpoint.
        - Edge case to consider: what if the user repeatedly hits the browser refresh button, or someone DDOS our website? Shouldn't we skip counting those as a valid visitor?
        - Perhaps we could track that by using a sliding window to look up the recent visits by UUID (say the UUID is generated by a unique combination like `{deviceID}-{IP-address}`), then avoid counting
        if there's a recent request within 1000 ms left window (1000 ms ago).
      */}
      <h1 className="text-sky-500">Visit Counter</h1>
    </div>
  );
}

export default App;
