import "./index.css";
import axios from "axios";
import { useState, useEffect, useRef } from "react";
import { GET_BACKEND_URL } from "./constants";

export interface VisitCounterResp {
  ok: boolean;
  visitors: number;
  errorMessage: string | undefined;
}

export function App() {
  const isDev =
    window.location.hostname === "localhost" ||
    window.location.hostname === "127.0.0.1";
  const BACKEND_URL = GET_BACKEND_URL(isDev);
  console.log("BACKEND_URL = ", BACKEND_URL, "\n");
  const [visitCnt, setVisitCnt] = useState<number | undefined>(undefined);
  // to prevent double-calling the endpoint in React StrictMode (only in development)
  const hasRun = useRef(false);

  useEffect(() => {
    if (hasRun.current) return;
    hasRun.current = true;

    axios
      .post(BACKEND_URL + "/visitor")
      .then((resp) => {
        const data: VisitCounterResp = resp.data;
        if (!data.ok) {
          throw new Error(data.errorMessage);
        }

        setVisitCnt(data.visitors);
      })
      .catch((err) => {
        console.log("error getting the visit count: ", err);
      });
  }, []);

  return (
    <div className="app">
      {/*
      we should call the backend here to get the visitor count.
      Flow:
      - When an user accesses a page, call the post endpoint to bump the visit counter by 1.
      - Then, return the counter from the endpoint.
        - Edge case to consider: what if the user repeatedly hits the browser refresh button, or someone DDOS our website? Shouldn't we skip counting those as a valid visitor?
        - Perhaps we could track that by using a sliding window to look up the recent visits by UUID (say the UUID is generated by a unique combination like `{deviceID}-{IP-address}`), then avoid counting
        if there's a recent request within 1000 ms left window (1000 ms ago).
      */}
      <h1 className="text-sky-500">
        {visitCnt === undefined
          ? "Loading..."
          : `The number of visitors is ${visitCnt}`}
      </h1>
    </div>
  );
}

export default App;
